### PR TITLE
Deploy jenkins slave private keys FLOC-4024

### PR DESCRIPTION
**Pull request by Azulinho**
Deploy the jenkins slave private key to the slaves so that they can clone private repositories

### CODE REVIEW

**Comment by james-w** [comment]
This is the same private key that is used to access slave EC2 instances?

If so then it seems like they should be separate keys. However, given that
controlling a Jenkins slave allows you to control the master maybe
it's not worth trying to separate out the roles further.

**Comment by Azulinho** [comment]
we need a proper management framework for managing secrets, unfortunately I haven't been able to push that priority upwards so far

**Comment by james-w** [comment]
Is this the same private key that is used to access slave EC2 instances?

**Comment by Azulinho** [comment]
yeap, same one

**Comment by james-w** [comment]
:heavy_check_mark: ok, go ahead

**Pull request merged**
